### ISSUE TITLE
Does this work with WordPress v6 or v5 only?

### ISSUE THREAD

**Issue by brandonros** [aaemnnosttv/wp-sqlite-db#41]

**Comment by aaemnnosttv** [comment]
Both 😄

**Comment by brandonros** [comment]
```yaml
version: '3.1'

services:

  wordpress:
    image: wordpress:6-php7.4-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html
      - ${PWD}/db.php:/var/www/html/wp-content/db.php
      - type: bind
        source: ./db.sqlite
        target: /var/www/html/db.sqlite
volumes:
  wordpress:
```

doesn't exactly work

even after

```php
define('USE_MYSQL', false);
define('DB_DIR', '/var/www/html/database');
define('DB_FILE', 'db.sqlite');
```

**Comment by brandonros** [comment]
docker-compose example

```yaml
version: '3.1'

services:

  wordpress:
    image: wordpress:6-php7.4-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html
      - ${PWD}/db.php:/var/www/html/wp-content/db.php
      - type: bind
        source: ./db.sqlite
        target: /var/www/html/db.sqlite
volumes:
  wordpress:
```

and then I just changed a few lines in db.php

```
namespace WP_SQLite_DB {

    use DateTime;
    use DateInterval;
    use PDO;
    use PDOException;

    if (! defined('ABSPATH')) {
        exit;
    }

    define('USE_MYSQL', false);
    define('DB_DIR', '/var/www/html/');
    define('DB_FILE', 'db.sqlite');
```

should probably put those variables in a different file i'm guessing?
